# Generated by Django 6.0 on 2026-01-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
        ('usuarios', '0003_alter_permiso_usuario_permiso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato_jefa',
            name='elecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_jefa_elecciones', to='elecciones.elecciones'),
        ),
        migrations.AlterField(
            model_name='candidato_jefa',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_jefa_persona', to='usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='candidato_jefe',
            name='elecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_jefe_elecciones', to='elecciones.elecciones'),
        ),
        migrations.AlterField(
            model_name='candidato_jefe',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_jefe_persona', to='usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='candidato_materiales',
            name='elecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_materiales_elecciones', to='elecciones.elecciones'),
        ),
        migrations.AlterField(
            model_name='candidato_materiales',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_materiales_persona', to='usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='elecciones',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elecciones', to='elecciones.periodo'),
        ),
        migrations.AlterField(
            model_name='urna',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urnas_area', to='usuarios.area'),
        ),
        migrations.AlterField(
            model_name='urna',
            name='elecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urnas_elecciones', to='elecciones.elecciones'),
        ),
        migrations.AlterField(
            model_name='urna',
            name='genero',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='urna',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urna_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voto',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_persona', to='usuarios.persona'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='urna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_urna', to='elecciones.urna'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_jefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_jefa', to='elecciones.candidato_jefa'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_jefe', to='elecciones.candidato_jefe'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_materiales', to='elecciones.candidato_materiales'),
        ),
    ]
