# Generated by Django 6.0 on 2026-01-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_alter_candidato_jefa_elecciones_and_more'),
        ('usuarios', '0007_alter_permiso_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato_jefe',
            name='elecciones',
        ),
        migrations.RemoveField(
            model_name='candidato_jefe',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='candidato_materiales',
            name='elecciones',
        ),
        migrations.RemoveField(
            model_name='candidato_materiales',
            name='persona',
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JCM', 'Jefe de Campamento'), ('JCF', 'Jefa de Campamento'), ('JM', 'Jefe(a) de Materiales')], max_length=3)),
                ('elecciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_materiales_elecciones', to='elecciones.elecciones')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_materiales_persona', to='usuarios.persona')),
            ],
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_jefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_jefa', to='elecciones.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_jefe', to='elecciones.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto_materiales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_materiales', to='elecciones.candidato'),
        ),
        migrations.DeleteModel(
            name='Candidato_Jefa',
        ),
        migrations.DeleteModel(
            name='Candidato_Jefe',
        ),
        migrations.DeleteModel(
            name='Candidato_Materiales',
        ),
    ]
