# Generated by Django 6.0 on 2026-01-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='clave_temporal',
            field=models.BooleanField(default=True),
        ),
    ]
