# Generated by Django 6.0 on 2026-01-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_persona_clave_temporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso_usuario',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.permiso'),
        ),
        migrations.AlterField(
            model_name='permiso_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='usuarios.area'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
