# Generated by Django 6.0 on 2026-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_permiso_usuario_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
