# Generated by Django 6.0 on 2026-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_permiso_usuario_permiso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
