# Generated by Django 6.0 on 2026-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permiso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
